name: Block PR to main

on:
  pull_request:
    branches:
      - main

jobs:
  block_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Block PR to main
        run: |
          echo "Direct PRs to 'main' are not allowed. Please redirect to the appropriate branch."
          exit 1
